#manejo de errores y excepciones:
try:
    print("hola")
except Exception as e:
    print(e)

finally:
    print("esto siempre se muestra")